# ~/.circleci/config.yml
version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      # Restore dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      # Install project dependencies
      - run: 
          name: Install dependencies
          command: npm i
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
      - run: npm run codecov
  release:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      # Restore dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      # Install project dependencies
      - run: 
          name: Install dependencies
          command: npm i
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: rm -rf lib
      - run: npm run build
      - run: npm run release

workflows:
  version: 2
  test_and_release:
    jobs:
      - test
      - release:
          filters:
            branches:
              only: master
